services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: mohit_user
      POSTGRES_PASSWORD: neon_password
      POSTGRES_DB: taskmaster_db
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://mohit_user:neon_password@db:5432/taskmaster_db?schema=public"
      JWT_SECRET: "your_super_secret_neon_key_123"
    depends_on:
      - db
    command: sh -c "npx prisma db push && npm start"